export enum SkillCategoryEnums {
  TECHNICAL = "technical", // Programming, databases, tools ...
  SOFT = "soft", // Communication, teamwork, problem-solving ...
  LANGUAGE = "language", // English, Uzbek, Russian ...
  MANAGEMENT = "management", // Leadership, time management, planning ...
}