export enum SkillCategoryEnums {
  TECHNICAL = "TECHNICAL", // Programming, databases, tools ...
  SOFT = "SOFT", // Communication, teamwork, problem-solving ...
  LANGUAGE = "LANGUAGE", // English, Uzbek, Russian ...
  MANAGEMENT = "MANAGEMENT", // Leadership, time management, planning ...
}